backend:
  name: git-gateway
  branch: master

media_folder: "site/static/img"
public_folder: "img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
